### ISSUE TITLE
[2pt] Create the Home Page (rooms page)

### ISSUE THREAD

**Issue by adel-gu** [adel-gu/Cherry-Rooms-front-end#3]
- Create a home page that displays a list of rooms.
- Add a horizontal slider for the room items.
- Each room card should behave as a link that leads to the room detail page.
- Add unit testing.

## The Design
![Image](https://user-images.githubusercontent.com/68030297/220922541-50562aa4-0e37-478e-9d9b-2d08ed918c04.png)

**Comment by Zuhaib042** [comment]
@Joel-100  can you please check this PR out.
https://github.com/adel-gu/Cherry-Rooms-front-end/pull/12
