### ISSUE TITLE
[2pt] Create and style the Panel component (Side NavBar)

### ISSUE THREAD

**Issue by adel-gu** [adel-gu/Cherry-Rooms-front-end#6]
- Create the Side NavBar, and ensure the styling is aligned with the design provided below
- In the navigation panel, the user can see links to:
    - Rooms
    - Add a reservation
    - My reservations
    - Add a room
    - Delete a room
    - Log out button

- Add unit testing.

### The Design:
![Image](https://user-images.githubusercontent.com/68030297/220919634-310a3860-28b3-454f-a4ef-46e63880d20a.png)

**Comment by Joel-100** [comment]
https://github.com/adel-gu/Cherry-Rooms-front-end/pull/11
