### ISSUE TITLE
[2pt] Create the Room Detail page

### ISSUE THREAD

**Issue by adel-gu** [adel-gu/Cherry-Rooms-front-end#7]
- The detail page should have
   - An image of the room
   - Information about the room
   - A reservation button
- Add unit testing.

![Image](https://user-images.githubusercontent.com/68030297/220923049-34779793-fbb5-4ed0-aeb2-99a24aca925d.png)

**Comment by Zuhaib042** [comment]
Hello @arabiu033, can you please take a look at this pull request
https://github.com/adel-gu/Cherry-Rooms-front-end/pull/15
